name: goride
description: GoRide - Unified Customer & Driver App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.3
  googleapis_auth: ^1.6.0

  # UI & Utils
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  bottom_picker: ^2.8.0

  flutter_dash: ^1.0.0
  provider: ^6.1.2
  dotted_border: ^2.1.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  video_player: ^2.9.2
  flutter_email_sender: ^6.0.3
  flutter_html: any
  share_plus: ^10.1.0
  map_launcher: ^3.5.0
  fluttercontactpicker: ^5.0.0
  google_maps_place_picker_mb: ^3.1.2
  badges: ^3.1.2
  location: any

  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.3.4
  translator: ^1.0.0

  # Payment dependencies
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.7
  flutter_paypal_native: ^2.1.0

dependency_overrides:
  webview_flutter: ^4.10.0
  http: ^1.2.2
  js: ^0.7.1
  stripe_platform_interface: ^10.1.1
  flutter_spinkit: 5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
